from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime
import pandas as pd

# -- Imports of your modules --
from src.scripts.eda_sales import sales_explorer
from src.scripts.transformation import sales_etl
from src.scripts.modeling import modeler
from src.database.loader import data_loader
from src.config.connectionPostgres import get_connection


def run_full_pipeline():
  print("--- Amausoft Pipeline: Starting execution ---", flush=True)

  # Ingestion (Raw Data)
  sales_etl.extract()
  df_raw = pd.read_csv("data/sales_data_sample.csv", encoding="ISO-8859-1")

  # EDA (Analysis of raw data)
  print("[EDA] Running deep exploration on raw data...", flush=True)
  sales_explorer.run_professional_eda(df_raw)

  # ETL (Cleaning and transformation)
  print("[ETL] Cleaning and transforming sales data...", flush=True)
  df_sales_clean = sales_etl.transform(df_raw)
  sales_etl.load(df_sales_clean)

  # Local data consumption (Generated by the Main)
  print("[Data] Loading local datasets from Main service...", flush=True)
  df_clients = pd.read_csv("data/clients_dataset.csv")
  df_regions = pd.read_csv("data/regions_master.csv")

  # Star Modeling (Geographic Integration)
  print("[Modeling] Building Star Schema with geographical coherence...", flush=True)
  modeler.build_star_schema(df_sales_clean, df_clients, df_regions)

  # Load to Postgres
  print("[DB] Loading dimensions and facts to PostgreSQL...", flush=True)
  conn = get_connection()
  try:
    tables = ["dim_regions", "dim_products", "dim_clients", "fact_sales"]
    for table in tables:
      csv_path = f"data/processed/{table}.csv"
      data_loader.bulk_insert(conn, csv_path, table)
    print("[DAG] Success: All data loaded into Postgres", flush=True)
  except Exception as e:
    print(f"[DAG] Error during DB load: {e}", flush=True)
    raise e
  finally:
    conn.close()


with DAG(
    dag_id="amausoft_automated_pipeline",
    start_date=datetime(2026, 4, 1),
    schedule_interval="@daily",
    catchup=False
) as dag:
  task_full_process = PythonOperator(
    task_id="full_data_orchestration",
    python_callable=run_full_pipeline
  )